---
- name: Transfer and execute a script.
  hosts: app 
  remote_user: root 
  sudo: yes
  tasks:
     - name: Transfer the script
       copy: src=install-py.sh dest=/webapps/devops/devops-challenge mode=0777

     - name: Execute the script
       command: sh /webapps/devops/devops-challenge/install-py.sh 
