--
- name: Transfer and execute a script.
  hosts: app 
  remote_user: root 
  sudo: yes
  tasks:
     - name: Transfer the script
       copy: src=git-install.sh dest=/root mode=0777

     - name: Execute the script
       command: sh /root/git-install.sh

- name: Transfer and execute a script.
  hosts: app 
  remote_user: root 
  sudo: yes
  tasks:
     - name: Transfer the script
       copy: src=git-co.sh dest=/root mode=0777

     - name: Execute the script
       command: sh /root/git-co.sh
